### ISSUE TITLE
Questions / Documentation

### ISSUE THREAD

**Issue by Excel1** [timnolte/oidc-keycloak-sso#1]
Hello,

i have some question about the functionality of this plugin:

1. If i download the repo and install the Plugin would it work?
Cause i did it like this and i see the new Inputfields and dropdown for the IDP Roles but it didnt work. I selected the default role    and everytime i register me the user role wasnt effected by the Plugin. (The selected default was Administrator) Do i miss some Settings or Hooks?

2. Would the Plugin take only the general Role or also the user client Role (Keycloak / OIDC)?
Maybe there could be an option to choose general or the plug in the client name

3. The Idea of this Plugin is great and can be used for more than just only Keycloak: Why would this not implemented directly to the OIDC Plugin with op-in option?

4. If i did some things wrong then maybe a documentation would be helpful ^^

**Comment by timnolte** [comment]
1. In general, if you are seeing the new fields after dropping this into the `mu-plugins` directory then you do have it installed correctly. The plugin should work with Keycloak once configured. Can you provide me more details on all of what you configured? These customizations were made with some very specific use cases in mind so it's possible you don't have it fully configured. Do you configure the role mappings for any of the WordPress roles?

2. The Keycloak roles will be looked for in the `user-realm-role` attribute in the user claim. I'm not quite sure what you mean by "General Role" or "User Client Role".

3. I'm not sure what you mean by picking general or plugin client name? Which configured attribute are you referring to?

4. So there are some aspects of this addon that could be used outside of Keycloak however there is code that isn't generic enough, like the `user-realm-role`, which wouldn't work outside of Keycloak, or this specific implementation. That aspect could be further extrapolated but part of the premise of this addon is to show the flexibility in customization that the main plugin provides. The intended audience is more of for developers/integrators that need a groundwork for setting up their IDP integration. From testing that I've done with various IDPs I've seen that each may have it's own variation on how they implemented OIDC.

5. To reiterate, this plugin was intended to show what customizations can be done by any developer for theaim plugin so this wasn't really intended to be used by someone that needed instructions in how to configure it work.

**Comment by Excel1** [comment]
1. I installed and configured the  OIDC Generic Plugin successfull and the login works. I installed the oidc-keycloak-sso and only set default role to administrator, but it didnt worked. Later i inserted 'test' in the IDP Administrator field and also set test as a role to my user but it also didnt worked. Do i need to set every Wordpress roles to a Keycloak role?

2. In Keycloak it is possible to set Client Roles for the user: Realm > Clients> *Clientname* > Roles. 
    
3, I thought this could be merged in the OIDC Generic Plugin but with OptIn Option. So i can choose which IDP i use and can select Keycloak to get these configuration options instead of a second plugin

4. Okay but i think it has some potential to be used ^^

5. Will the Wordpress Roles overwritten / new set if i got registered and change the mapped role in keycloak

Thanks for answering!

**Comment by derBobby** [comment]
I will try to light up this issue a bit: In KC you can add roles to a user:
- for the client scope
- for the realm scope

Both roles are not by default in the "use-realm-role" segment of the auth token.
This can e.g. be achieved like in the screenshot in my own issue.

This is the auth token WITH the role mapping adjustment:
```
{
  "exp": 1610857312,
  "iat": 1610857012,
  "jti": "removed",
  "iss": "https://<server>/auth/realms/<realm>",
  "aud": "account",
  "sub": "removed",
  "typ": "Bearer",
  "azp": "<realm>",
  "session_state": "removed",
  "acr": "1",
  **"realm_access":** {
    "roles": [
      "offline_access",
      "uma_authorization",
      **"this_is_a_realm_role"**
    ]
  },
  "resource_access": {
    **"<client_id>"**: {
      "roles": [
        **"this_is_a_client_role"**
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid profile email",
  "email_verified": true,
  **"user-realm-role": [**
    **"this_is_a_client_role"**     <---- Role mapping, see my screenshot
  ],
  "name": "der Bobby",
  "preferred_username": "removed",
  "given_name": "der",
  "family_name": "Bobby",
  "email": "removed"
}
```

Plug and play solution for KC, but maybe not other IDPs, could be two checkboxes:
- "use resource_access" to use roles from the KC oidc client
- "use realm_access" to use roles from the KC realm

Other option would be to make _user-realm-role_ configurable so that it would be possible to configure the two leafs from the auth token tree.

**Comment by timnolte** [comment]
@derBobby I was wondering where this other comment of yours was as it seemed to be missing from the other issue, ha. So the short of some of these questions is that I'd be happy to support additional changes to this code if it means more people could just drop it in and use it. I'm a bit swamped with much needed changes to the actual plugin as well as another WordPress plugin of mine so I don't have a ton of time to work on this. I will look at making updates as I can.

**Comment by Excel1** [comment]
Maybe we can split this issue (development ideas) into smaller issues. So its easier for other people to help and also its possible to discuss about every single idea.

**Comment by TBG-FR** [comment]
> I will try to light up this issue a bit: In KC you can add roles to a user:
> 
> * for the client scope
> * for the realm scope
> 
> Both roles are not by default in the "use-realm-role" segment of the auth token. This can e.g. be achieved like in the screenshot in my own issue.
> 
> This is the auth token WITH the role mapping adjustment:
> 
> ```
> {
>   "exp": 1610857312,
>   "iat": 1610857012,
>   "jti": "removed",
>   "iss": "https://<server>/auth/realms/<realm>",
>   "aud": "account",
>   "sub": "removed",
>   "typ": "Bearer",
>   "azp": "<realm>",
>   "session_state": "removed",
>   "acr": "1",
>   **"realm_access":** {
>     "roles": [
>       "offline_access",
>       "uma_authorization",
>       **"this_is_a_realm_role"**
>     ]
>   },
>   "resource_access": {
>     **"<client_id>"**: {
>       "roles": [
>         **"this_is_a_client_role"**
>       ]
>     },
>     "account": {
>       "roles": [
>         "manage-account",
>         "manage-account-links",
>         "view-profile"
>       ]
>     }
>   },
>   "scope": "openid profile email",
>   "email_verified": true,
>   **"user-realm-role": [**
>     **"this_is_a_client_role"**     <---- Role mapping, see my screenshot
>   ],
>   "name": "der Bobby",
>   "preferred_username": "removed",
>   "given_name": "der",
>   "family_name": "Bobby",
>   "email": "removed"
> }
> ```
> 
> Plug and play solution for KC, but maybe not other IDPs, could be two checkboxes:
> 
> * "use resource_access" to use roles from the KC oidc client
> * "use realm_access" to use roles from the KC realm
> 
> Other option would be to make _user-realm-role_ configurable so that it would be possible to configure the two leafs from the auth token tree.

Using https://github.com/timnolte/oidc-keycloak-sso/pull/4 you should be able to read client roles (I did it successfully) and also realm roles (not tested because they do not appear in my token, I may have missed a setting in Keycloak, **but should work as well !**). Enjoy 🤙
